package com.medical.demo.mapper;

import com.medical.demo.model.DoctorDutyExample;
import com.medical.demo.model.DoctorDutyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DoctorDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    long countByExample(DoctorDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int deleteByExample(DoctorDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int deleteByPrimaryKey(DoctorDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int insert(DoctorDutyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int insertSelective(DoctorDutyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    List<DoctorDutyKey> selectByExampleWithRowbounds(DoctorDutyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    List<DoctorDutyKey> selectByExample(DoctorDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") DoctorDutyKey record, @Param("example") DoctorDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByExample(@Param("record") DoctorDutyKey record, @Param("example") DoctorDutyExample example);
}