package com.medical.demo.mapper;

import com.medical.demo.model.Duty;
import com.medical.demo.model.DutyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    long countByExample(DutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int deleteByExample(DutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int insert(Duty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int insertSelective(Duty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    List<Duty> selectByExampleWithRowbounds(DutyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    List<Duty> selectByExample(DutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    Duty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Duty record, @Param("example") DutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByExample(@Param("record") Duty record, @Param("example") DutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByPrimaryKeySelective(Duty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    int updateByPrimaryKey(Duty record);
}