package com.medical.demo.model;

public class DoctorDutyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_duty.doctorId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_duty.dutyId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer dutyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_duty.doctorId
     *
     * @return the value of doctor_duty.doctorId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_duty.doctorId
     *
     * @param doctorid the value for doctor_duty.doctorId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_duty.dutyId
     *
     * @return the value of doctor_duty.dutyId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getDutyid() {
        return dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_duty.dutyId
     *
     * @param dutyid the value for doctor_duty.dutyId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setDutyid(Integer dutyid) {
        this.dutyid = dutyid;
    }
}