package com.medical.demo.model;

public class Duty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty.time
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty.id
     *
     * @return the value of duty.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty.id
     *
     * @param id the value for duty.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty.parentId
     *
     * @return the value of duty.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty.parentId
     *
     * @param parentid the value for duty.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty.time
     *
     * @return the value of duty.time
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty.time
     *
     * @param time the value for duty.time
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}