package com.medical.demo.model;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.identity
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.token
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.userId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.id
     *
     * @return the value of patient.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.id
     *
     * @param id the value for patient.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.identity
     *
     * @return the value of patient.identity
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.identity
     *
     * @param identity the value for patient.identity
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.token
     *
     * @return the value of patient.token
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.token
     *
     * @param token the value for patient.token
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.userId
     *
     * @return the value of patient.userId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.userId
     *
     * @param userid the value for patient.userId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}