package com.medical.demo.model;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.user_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.doc_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.dep_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.duty_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer dutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.status
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.id
     *
     * @return the value of register.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.id
     *
     * @param id the value for register.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.user_id
     *
     * @return the value of register.user_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.user_id
     *
     * @param userId the value for register.user_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.doc_id
     *
     * @return the value of register.doc_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.doc_id
     *
     * @param docId the value for register.doc_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.dep_id
     *
     * @return the value of register.dep_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.dep_id
     *
     * @param depId the value for register.dep_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.duty_id
     *
     * @return the value of register.duty_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.duty_id
     *
     * @param dutyId the value for register.duty_id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setDutyId(Integer dutyId) {
        this.dutyId = dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.status
     *
     * @return the value of register.status
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.status
     *
     * @param status the value for register.status
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}