package com.medical.demo.model;

public class SysPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.name
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.css
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String css;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.href
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.type
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parentId
     *
     * @return the value of sys_permission.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parentId
     *
     * @param parentid the value for sys_permission.parentId
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.name
     *
     * @return the value of sys_permission.name
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.name
     *
     * @param name the value for sys_permission.name
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.css
     *
     * @return the value of sys_permission.css
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.css
     *
     * @param css the value for sys_permission.css
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setCss(String css) {
        this.css = css == null ? null : css.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.href
     *
     * @return the value of sys_permission.href
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.href
     *
     * @param href the value for sys_permission.href
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.type
     *
     * @return the value of sys_permission.type
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.type
     *
     * @param type the value for sys_permission.type
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission
     *
     * @return the value of sys_permission.permission
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission
     *
     * @param permission the value for sys_permission.permission
     *
     * @mbg.generated Wed Mar 25 21:06:10 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}